### ISSUE TITLE
Question about forecasting

### ISSUE THREAD

**Issue by AsierRGdD** [eromoe/base#1]
Hi eromoe...

I have been reading some post where you commented in the past related to forecasting with prophet, such as: 

https://github.com/facebook/prophet/issues/1734

I am facing the same problem and I would love to know how you solved it. In my brain the perfect solution fits with your initial question, something like a multivariate model with shared regressors. 

Did you research more about this?

I want to apologize myself because of writing you by this way, but it is the only contacting method that I found.

Thanks in advance. Regards

**Comment by eromoe** [comment]
Unfortunately I changed work after few weeks post that issue, there is no further research .
I think [bletham](https://github.com/bletham)'s recommendation is more promising, you could have a try.
